# -*- coding: utf-8 -*-
"""2020-03-27week3,4--A104260271--homework.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gUSiB47mlk39pT5dCZRG87oz4d4whF5U
"""

movie_title = "陽光普照"
movie_rating = 7.7
movie_time = 156

print(movie_title)
print(movie_rating)
print(movie_time)

print(type(movie_title))
print(type(movie_rating))
print(type(movie_time))

movie_time_hour = 2
movie_time_min = 36
movie_time_min = movie_time_min + movie_time_hour * 60
print(movie_time_min)

print ("I'm lovin' it")

ross_said = """
Let's put aside the fact that you "accidentally" pick up my grandmother's ring.
"""
print(ross_said)
print(type(ross_said))

ross_said = """Let's put aside the fact that you "accidentally" pick up my grandmother's ring."""
print(ross_said)

shaq = 'Shaquille O\'Neal'
print(shaq)
print(type(shaq))

current_celsius = 28
current_fahrenheit = current_celsius * 9 / 5 + 32
print(current_fahrenheit)

shaq_height = 216
shaq_weight = 147
shaq_bmi = shaq_weight / (shaq_height/100)**2
print(shaq_bmi)

city_name = input()
city_weather = input()
print ("我在" + city_name + "天氣" + city_weather)

player_name = input("球員名")
player_height = float (input("球員身高"))
player_weight = float (input("球員體重"))
player_bmi = player_weight / (player_height/100)**2
player_bmi = float (player_bmi)
if player_bmi > 35:
  print("{}的BMI為{} ,重度肥胖！" .format(player_name, player_bmi))
elif player_bmi > 27:
  print("{}的BMI為{} ,肥胖！" .format(player_name, player_bmi))
else:
  print("{}的BMI為 {} ,SAFE!".format(player_name, player_bmi))

