# -*- coding: utf-8 -*-
"""week4_A104260271.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xwg9GJ2auKLL3FCh585wTCKV6JSrYcMU
"""

print('Hello World')

print('你好嗎')

print('Hello World')
print('你好嗎')

